### ISSUE TITLE
[UI] Checklist de Desafios

### ISSUE THREAD

**Issue by lcardosott** [Joaotakaki1/mc656-final-project#25]
#30 
## User Storie
Como usuário eu gostaria de ver os desafios em aberto

## Descrição
Com base no desafio diario gerado, crie um widget que funcione como uma Checklist. Nele você podera marcar um desafio como concluido, ou não.

## Passos importantes
- [ ] Colete as informações do desafio
- [ ] Se clicar na bolinha da task risca
- [ ] Se clicar na bolinha dnv desrisca

## Imagens
![image](https://github.com/user-attachments/assets/f58cc061-350b-4838-9f6f-84ca6ecf30d7)
